version: "3.7"

services:
  db:
    image: mysql:5.7
    container_name: black-armory-db
    volumes:
      - my-db:/var/lib/mysql
    env_file: ./.env #Here we are using the already existing .env.local file
    ports:
      - "3306:3306"

volumes:
  my-db:

