version: "3.7"

services:
  db:
    image: postgres:latest
    container_name: black-armory-db
    volumes:
      - data:/var/lib/postgresql/data
    env_file: ./.env.local #Here we are using the already existing .env.local file
    ports:
      - "5433:5432"

volumes:
  data: